/*
 * RentSpot — rental property dataset.
 * Shared between the home page (app.js) and the detail page (property.js).
 *
 * All monetary values are in Indian Rupees (INR).
 * All proximity values (metro, railway, hospital, school) are in kilometres.
 * `available` is an ISO date string; a date in the past (or today) means the
 * property is available immediately.
 */
window.PROPERTIES = [
  {
    id: 1,
    title: "Spacious 2BHK Apartment",
    type: "2 BHK Apartment",
    city: "Bengaluru",
    locality: "Koramangala",
    rent: 32000,
    advance: 160000,
    available: "2024-01-01",
    area: 1150,
    furnishing: "Semi-Furnished",
    bedrooms: 2,
    bathrooms: 2,
    metro: 1.2,
    railway: 6.5,
    hospital: 0.8,
    school: 0.6,
    hue: 210,
    description:
      "A bright, airy 2BHK in the heart of Koramangala with a large balcony, modular kitchen and covered parking. Walking distance to cafes, co-working spaces and the metro.",
    amenities: ["Covered Parking", "24x7 Security", "Power Backup", "Lift", "Gym", "Piped Gas"],
  },
  {
    id: 2,
    title: "Sea-Facing 3BHK Flat",
    type: "3 BHK Apartment",
    city: "Mumbai",
    locality: "Bandra West",
    rent: 95000,
    advance: 570000,
    available: "2024-03-15",
    area: 1450,
    furnishing: "Fully-Furnished",
    bedrooms: 3,
    bathrooms: 3,
    metro: 2.4,
    railway: 1.1,
    hospital: 1.5,
    school: 0.9,
    hue: 200,
    description:
      "Premium sea-facing residence in Bandra West with panoramic Arabian Sea views, imported fittings and a clubhouse. Minutes from Bandra station and the Bandra-Worli Sea Link.",
    amenities: ["Sea View", "Swimming Pool", "Clubhouse", "Reserved Parking", "Concierge", "Power Backup"],
  },
  {
    id: 3,
    title: "Cozy 1BHK Studio",
    type: "1 BHK Apartment",
    city: "Pune",
    locality: "Hinjewadi",
    rent: 18500,
    advance: 74000,
    available: "2024-01-01",
    area: 620,
    furnishing: "Semi-Furnished",
    bedrooms: 1,
    bathrooms: 1,
    metro: 4.2,
    railway: 12.0,
    hospital: 1.2,
    school: 1.8,
    hue: 145,
    description:
      "Compact and efficient 1BHK ideal for IT professionals, located inside a gated society in Hinjewadi Phase 1. Close to major tech parks and everyday conveniences.",
    amenities: ["Gated Community", "Parking", "Power Backup", "Lift", "Gym"],
  },
  {
    id: 4,
    title: "Modern 3BHK Villa",
    type: "3 BHK Villa",
    city: "Hyderabad",
    locality: "Gachibowli",
    rent: 55000,
    advance: 330000,
    available: "2024-02-10",
    area: 2100,
    furnishing: "Fully-Furnished",
    bedrooms: 3,
    bathrooms: 4,
    metro: 3.0,
    railway: 9.5,
    hospital: 1.0,
    school: 0.5,
    hue: 25,
    description:
      "An elegant independent villa with a private garden, terrace and two-car garage in a premium Gachibowli enclave. Close to top international schools and the financial district.",
    amenities: ["Private Garden", "Terrace", "2-Car Garage", "24x7 Security", "Power Backup", "Piped Gas"],
  },
  {
    id: 5,
    title: "Budget 1BHK Home",
    type: "1 BHK Independent",
    city: "Chennai",
    locality: "Velachery",
    rent: 14000,
    advance: 42000,
    available: "2024-01-01",
    area: 560,
    furnishing: "Unfurnished",
    bedrooms: 1,
    bathrooms: 1,
    metro: 0.7,
    railway: 1.3,
    hospital: 1.4,
    school: 0.8,
    hue: 280,
    description:
      "Affordable independent 1BHK on the first floor of a quiet residential building in Velachery, a short walk from the MRTS station and Velachery metro connectivity.",
    amenities: ["Two-Wheeler Parking", "Water Supply 24x7", "Balcony"],
  },
  {
    id: 6,
    title: "Luxury 4BHK Penthouse",
    type: "4 BHK Penthouse",
    city: "Gurugram",
    locality: "Golf Course Road",
    rent: 140000,
    advance: 840000,
    available: "2024-04-01",
    area: 3200,
    furnishing: "Fully-Furnished",
    bedrooms: 4,
    bathrooms: 5,
    metro: 1.0,
    railway: 14.0,
    hospital: 2.0,
    school: 1.2,
    hue: 340,
    description:
      "Sprawling duplex penthouse with a private plunge pool, home theatre and skyline views on Golf Course Road. Direct access to the Rapid Metro and premium retail.",
    amenities: ["Private Pool", "Home Theatre", "Concierge", "Valet Parking", "Clubhouse", "Power Backup"],
  },
  {
    id: 7,
    title: "Family 2BHK Apartment",
    type: "2 BHK Apartment",
    city: "Delhi",
    locality: "Dwarka Sector 12",
    rent: 26000,
    advance: 104000,
    available: "2024-01-20",
    area: 1050,
    furnishing: "Semi-Furnished",
    bedrooms: 2,
    bathrooms: 2,
    metro: 0.5,
    railway: 8.0,
    hospital: 0.9,
    school: 0.4,
    hue: 190,
    description:
      "Well-maintained 2BHK in a DDA society at Dwarka Sector 12, right next to the metro station. Surrounded by reputed schools, hospitals and a neighbourhood market.",
    amenities: ["Metro Adjacent", "Parking", "Park", "Power Backup", "Lift", "24x7 Security"],
  },
  {
    id: 8,
    title: "Riverside 2BHK Flat",
    type: "2 BHK Apartment",
    city: "Kolkata",
    locality: "New Town",
    rent: 21000,
    advance: 84000,
    available: "2024-02-01",
    area: 980,
    furnishing: "Semi-Furnished",
    bedrooms: 2,
    bathrooms: 2,
    metro: 2.8,
    railway: 5.0,
    hospital: 1.1,
    school: 1.0,
    hue: 160,
    description:
      "Peaceful 2BHK in a modern New Town high-rise with landscaped gardens and a jogging track. Great connectivity to Salt Lake Sector V and the upcoming metro line.",
    amenities: ["Landscaped Garden", "Jogging Track", "Parking", "Gym", "Power Backup", "Lift"],
  },
  {
    id: 9,
    title: "Compact 2BHK near Tech Park",
    type: "2 BHK Apartment",
    city: "Bengaluru",
    locality: "Whitefield",
    rent: 27500,
    advance: 137500,
    available: "2024-01-01",
    area: 1080,
    furnishing: "Fully-Furnished",
    bedrooms: 2,
    bathrooms: 2,
    metro: 0.9,
    railway: 7.2,
    hospital: 0.7,
    school: 0.9,
    hue: 100,
    description:
      "Fully-furnished 2BHK a stone's throw from ITPL and the new Whitefield metro. Ready to move in with all appliances, ideal for working couples and small families.",
    amenities: ["Fully Furnished", "Metro Nearby", "Gym", "Swimming Pool", "Parking", "Power Backup"],
  },
  {
    id: 10,
    title: "Heritage 3BHK Bungalow",
    type: "3 BHK Independent",
    city: "Jaipur",
    locality: "C-Scheme",
    rent: 42000,
    advance: 168000,
    available: "2024-03-01",
    area: 1900,
    furnishing: "Semi-Furnished",
    bedrooms: 3,
    bathrooms: 3,
    metro: 1.6,
    railway: 3.5,
    hospital: 0.6,
    school: 0.7,
    hue: 40,
    description:
      "Charming independent bungalow with courtyard in the upscale C-Scheme locality. Wide roads, mature trees and central to Jaipur's best hospitals and schools.",
    amenities: ["Courtyard", "Car Parking", "Servant Quarter", "Power Backup", "Piped Gas"],
  },
  {
    id: 11,
    title: "Smart 1BHK Apartment",
    type: "1 BHK Apartment",
    city: "Ahmedabad",
    locality: "SG Highway",
    rent: 16000,
    advance: 64000,
    available: "2024-01-10",
    area: 640,
    furnishing: "Semi-Furnished",
    bedrooms: 1,
    bathrooms: 1,
    metro: 1.4,
    railway: 6.8,
    hospital: 1.3,
    school: 1.5,
    hue: 260,
    description:
      "Modern 1BHK on SG Highway with quick access to business hubs, malls and the metro corridor. Efficient layout with a functional kitchen and dedicated parking.",
    amenities: ["Parking", "Lift", "Power Backup", "Gym", "24x7 Security"],
  },
  {
    id: 12,
    title: "Premium 3BHK Apartment",
    type: "3 BHK Apartment",
    city: "Bengaluru",
    locality: "Indiranagar",
    rent: 68000,
    advance: 408000,
    available: "2024-02-20",
    area: 1600,
    furnishing: "Fully-Furnished",
    bedrooms: 3,
    bathrooms: 3,
    metro: 0.6,
    railway: 5.5,
    hospital: 0.5,
    school: 0.8,
    hue: 320,
    floor: "9th of 15",
    facing: "East",
    age: "4 years",
    contact: "+91 98450 88990",
    description:
      "Upscale 3BHK in vibrant Indiranagar, steps from 100 Feet Road and the metro. Designer interiors, private terrace access and a rooftop lounge for residents.",
    amenities: ["Rooftop Lounge", "Metro Nearby", "Reserved Parking", "Gym", "Power Backup", "Concierge"],
  },
];
